language: python
python:
  - "nightly"
  - "3.7-dev"
  - "3.6-dev"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
install:
  - pip install --install-option='--no-cython-compile' Cython
  - pip install -r dev_requirements.txt
  - python setup.py develop
script:
  - python -m unittest discover -v tests
notifications:
  email:
      - brett.olsen+travis-ci@gmail.com
      - robert.kern+travis-ci@gmail.com
