# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=20 --max-line-length=127 --statistics

  build_and_test_sdist:
    name: Test sdist Python 3.8
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip 
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/build.txt
        python -m pip install -r requirements/tests.txt
    - name: Build sdist
      run: |
        python setup.py sdist
    - name: Install sdist
      run: |
        cd dist
        ls -al
        pip install line_profiler*.tar.gz -v
    - name: Test sdist
      run: |
        pwd
        ls -al
        # Ensure the source doesn't conflict with the test
        rm -rf line_profiler
        rm -rf kernprof.py  
        # cd ..
        python run_tests.py

    - name: Upload sdist artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist/*.tar.gz

  build_and_test_wheels:
    name: ${{ matrix.cibw_build }} on ${{ matrix.os }}, arch=${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        arch: [auto]
        cibw_build: [cp3*-*]
        cibw_skip: ["*-win32"]
        # Add additional workers to reduce overall build time
        include:
          - os: windows-latest
            cibw_build: cp3*-win32
            arch: auto
            cibw_skip: ""
          - os: ubuntu-latest
            arch: aarch64
            cibw_build: cp35-*
          - os: ubuntu-latest
            arch: aarch64
            cibw_build: cp36-*
          - os: ubuntu-latest
            arch: aarch64
            cibw_build: cp37-*
          - os: ubuntu-latest
            arch: aarch64
            cibw_build: cp38-*
          - os: ubuntu-latest
            arch: aarch64
            cibw_build: cp39-*


    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    # Configure compilers for Windows 64bit.
    - name: Enable MSVC 64bit
      if: matrix.os == 'windows-latest' && matrix.cibw_build != 'cp3*-win32'
      uses: ilammy/msvc-dev-cmd@v1
    
    # Configure compilers for Windows 32bit.
    - name: Enable MSVC 32bit
      if: matrix.os == 'windows-latest' && matrix.cibw_build == 'cp3*-win32'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    # Emulate aarch64 ppc64le s390x under linux
    - name: Set up QEMU
      if: runner.os == 'Linux' && matrix.arch != 'auto'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Build wheels
      uses: joerick/cibuildwheel@v1.12.0
      with:
        output-dir: wheelhouse
      # to supply options, put them in 'env', like:
      env:
        CIBW_SKIP: ${{ matrix.cibw_skip }}
        CIBW_BUILD: ${{ matrix.cibw_build }}
        CIBW_TEST_REQUIRES: -r requirements/tests.txt
        CIBW_TEST_COMMAND: python {project}/run_tests.py
        # configure cibuildwheel to build native archs ('auto'), or emulated ones
        CIBW_ARCHS_LINUX: ${{ matrix.arch }}

    - name: Show built files
      shell: bash
      run: ls -la wheelhouse

    - name: Set up Python 3.8 to combine coverage Linux
      if: runner.os == 'Linux'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Combine coverage Linux
      if: runner.os == 'Linux'
      run: |
        echo '############ PWD'
        pwd
        python -m pip install coverage[toml]
        echo '############ combine'
        coverage combine ./wheelhouse
        echo '############ XML'
        coverage xml -o ./tests/coverage.xml
        echo '############ FIND'
        find . -name .coverage.*
        find . -name coverage.xml

    - name: Codecov Upload
      uses: codecov/codecov-action@v1
      with:
        file: ./tests/coverage.xml

    - name: Upload wheels artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./wheelhouse/*.whl

  deploy:
    name: Uploading to PyPi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [build_and_test_wheels, build_and_test_sdist]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Download wheels and sdist
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: dist

      - name: Show files to upload
        shell: bash
        run: ls -la dist
      - name: Sign and Publish
        env:
          # Toggle comments to publish to the test pypi instead of the real one
          #TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
          #PYUTILS_TWINE_USERNAME: ${{ secrets.PYUTILS_TWINE_USERNAME }}
          #PYUTILS_TWINE_PASSWORD: ${{ secrets.PYUTILS_TWINE_PASSWORD }}
          TEST_TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
          PYUTILS_TEST_TWINE_USERNAME: ${{ secrets.PYUTILS_TEST_TWINE_USERNAME }}
          PYUTILS_TEST_TWINE_PASSWORD: ${{ secrets.PYUTILS_TEST_TWINE_PASSWORD }}
        run: |
          ls -al
          GPG_EXECUTABLE=gpg
          $GPG_EXECUTABLE --version
          openssl version
          $GPG_EXECUTABLE --list-keys
          export PYUTILS_CI_GITHUB_SECRET=${{ secrets.PYUTILS_CI_GITHUB_SECRET }}
          GLKWS=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/cci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
          GLKWS=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/cci_gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
          GLKWS=$PYUTILS_CI_GITHUB_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/cci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
          $GPG_EXECUTABLE --list-keys  || echo "first one fails for some reason"
          $GPG_EXECUTABLE --list-keys  
          MB_PYTHON_TAG=$(python -c "import setup; print(setup.MB_PYTHON_TAG)")
          VERSION=$(python -c "import setup; print(setup.VERSION)") 
          pip install twine
          pip install six pyopenssl ndg-httpsclient pyasn1 -U --user
          pip install requests[security] twine --user
          GPG_KEYID=$(cat dev/public_gpg_key)
          echo "GPG_KEYID = '$GPG_KEYID'"
          #
          #export TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/
          #export PYUTILS_TEST_TWINE_USERNAME=${{ secrets.PYUTILS_TEST_TWINE_USERNAME }}
          #export PYUTILS_TEST_TWINE_PASSWORD=${{ secrets.PYUTILS_TEST_TWINE_PASSWORD }}
          #MB_PYTHON_TAG=$MB_PYTHON_TAG \
          #    DO_GPG=True GPG_KEYID=$GPG_KEYID \
          #    TWINE_REPOSITORY_URL=${TWINE_REPOSITORY_URL} \
          #    TWINE_USERNAME=$PYUTILS_TEST_TWINE_USERNAME \
          #    TWINE_PASSWORD=$PYUTILS_TEST_TWINE_PASSWORD \
          #    GPG_EXECUTABLE=$GPG_EXECUTABLE \
          #    DO_UPLOAD=True \
          #    DO_TAG=False ./publish.sh
          #
          export TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
          export PYUTILS_TWINE_USERNAME=${{ secrets.PYUTILS_TWINE_USERNAME }}
          export PYUTILS_TWINE_PASSWORD=${{ secrets.PYUTILS_TWINE_PASSWORD }}
          MB_PYTHON_TAG=$MB_PYTHON_TAG \
              DO_GPG=True GPG_KEYID=$GPG_KEYID \
              TWINE_PASSWORD=$PYUTILS_TWINE_PASSWORD \
              TWINE_USERNAME=$PYUTILS_TWINE_USERNAME \
              GPG_EXECUTABLE=$GPG_EXECUTABLE \
              DO_UPLOAD=True \
              DO_TAG=False ./publish.sh 
       
###
# Unfortunately we cant (yet) use the yaml docstring trick here
# https://github.community/t/allow-unused-keys-in-workflow-yaml-files/172120
#__doc__: |
#    # How to run locally
#    # https://packaging.python.org/guides/using-testpypi/
#    cd $HOME/code
#    git clone https://github.com/nektos/act.git $HOME/code/act
#    cd $HOME/code/act
#    chmod +x install.sh
#    ./install.sh -b $HOME/.local/opt/act
#    cd $HOME/code/line_profiler

#    load_secrets
#    unset GITHUB_TOKEN
#    $HOME/.local/opt/act/act \
#        --secret=PYUTILS_TWINE_PASSWORD=$PYUTILS_TWINE_PASSWORD \
#        --secret=PYUTILS_TWINE_USERNAME=$PYUTILS_TWINE_USERNAME \
#        --secret=PYUTILS_CI_GITHUB_SECRET=$PYUTILS_CI_GITHUB_SECRET \
#        --secret=PYUTILS_TEST_TWINE_USERNAME=$PYUTILS_TEST_TWINE_USERNAME \
#        --secret=PYUTILS_TEST_TWINE_PASSWORD=$PYUTILS_TEST_TWINE_PASSWORD 
